import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import Sidebar from "@/shared/components/Sidebar";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${poppins.className} antialiased bg-foreground`}>
        <main className="h-dvh p-5 flex gap-3">
          <div className="h-full hidden sm:block w-[15%]">
            <Sidebar />
          </div>

          {children}
        </main>
      </body>
    </html>
  );
}
